// Browsers — 29 IDs → tier "read"
export const BROWSER_BUNDLE_IDS = new Set([
	"com.apple.Safari",
	"com.apple.SafariTechnologyPreview",
	"com.google.Chrome",
	"com.google.Chrome.beta",
	"com.google.Chrome.dev",
	"com.google.Chrome.canary",
	"com.microsoft.edgemac",
	"com.microsoft.edgemac.Beta",
	"com.microsoft.edgemac.Dev",
	"com.microsoft.edgemac.Canary",
	"org.mozilla.firefox",
	"org.mozilla.firefoxdeveloperedition",
	"org.mozilla.nightly",
	"org.chromium.Chromium",
	"com.brave.Browser",
	"com.brave.Browser.beta",
	"com.brave.Browser.nightly",
	"com.operasoftware.Opera",
	"com.operasoftware.OperaGX",
	"com.operasoftware.OperaDeveloper",
	"com.vivaldi.Vivaldi",
	"company.thebrowser.Browser",
	"company.thebrowser.dia",
	"org.torproject.torbrowser",
	"com.duckduckgo.macos.browser",
	"ru.yandex.desktop.yandex-browser",
	"ai.perplexity.comet",
	"com.sigmaos.sigmaos.macos",
	"com.kagi.kagimacOS",
]);

// Terminals/IDEs — 47 IDs → tier "click"
export const TERMINAL_BUNDLE_IDS = new Set([
	"com.apple.Terminal",
	"com.googlecode.iterm2",
	"dev.warp.Warp-Stable",
	"dev.warp.Warp-Beta",
	"com.github.wez.wezterm",
	"org.alacritty",
	"io.alacritty",
	"net.kovidgoyal.kitty",
	"co.zeit.hyper",
	"com.mitchellh.ghostty",
	"org.tabby",
	"com.termius-dmg.mac",
	"com.microsoft.VSCode",
	"com.microsoft.VSCodeInsiders",
	"com.vscodium",
	"com.todesktop.230313mzl4w4u92", // Cursor
	"com.exafunction.windsurf",
	"dev.zed.Zed",
	"dev.zed.Zed-Preview",
	"com.jetbrains.intellij",
	"com.jetbrains.intellij.ce",
	"com.jetbrains.pycharm",
	"com.jetbrains.pycharm.ce",
	"com.jetbrains.WebStorm",
	"com.jetbrains.CLion",
	"com.jetbrains.goland",
	"com.jetbrains.rubymine",
	"com.jetbrains.PhpStorm",
	"com.jetbrains.datagrip",
	"com.jetbrains.rider",
	"com.jetbrains.AppCode",
	"com.jetbrains.rustrover",
	"com.jetbrains.fleet",
	"com.google.android.studio",
	"com.axosoft.gitkraken",
	"com.sublimetext.4",
	"com.sublimetext.3",
	"org.vim.MacVim",
	"com.neovim.neovim",
	"org.gnu.Emacs",
	"com.apple.dt.Xcode",
	"org.eclipse.platform.ide",
	"org.netbeans.ide",
	"com.microsoft.visual-studio",
	"com.apple.ScriptEditor2",
	"com.apple.Automator",
	"com.apple.shortcuts",
]);

// Trading — 12 IDs → tier "read"
export const TRADING_BUNDLE_IDS = new Set([
	"com.webull.desktop.v1",
	"com.webull.trade.mac.v1",
	"com.tastytrade.desktop",
	"com.tradingview.tradingviewapp.desktop",
	"com.fidelity.activetrader",
	"com.fmr.activetrader",
	"com.install4j.5889-6375-8446-2021", // thinkorswim
	"com.binance.BinanceDesktop",
	"com.electron.exodus",
	"org.pythonmac.unspecified.Electrum",
	"com.ledger.live",
	"io.trezor.TrezorSuite",
]);

// Media — 19 IDs → BLOCKED (not granted any tier)
export const MEDIA_BUNDLE_IDS = new Set([
	"com.apple.TV",
	"com.apple.Music",
	"com.apple.iBooksX",
	"com.apple.podcasts",
	"com.spotify.client",
	"com.amazon.music",
	"com.tidal.desktop",
	"com.deezer.deezer-desktop",
	"com.pandora.desktop",
	"com.electron.pocket-casts",
	"au.com.shiftyjelly.PocketCasts",
	"tv.plex.desktop",
	"tv.plex.htpc",
	"tv.plex.plexamp",
	"com.amazon.aiv.AIVApp",
	"net.kovidgoyal.calibre",
	"com.amazon.Kindle",
	"com.amazon.Lassen",
	"com.kobo.desktop.Kobo",
]);

// Sentinel warnings — apps that trigger extra safety prompts
export const SHELL_SENTINELS = new Set([
	"com.apple.Terminal",
	"com.googlecode.iterm2",
	"com.microsoft.VSCode",
	"dev.warp.Warp-Stable",
	"dev.warp.Warp-Beta",
	"com.github.wez.wezterm",
	"org.alacritty",
	"io.alacritty",
	"net.kovidgoyal.kitty",
	"com.jetbrains.intellij",
	"com.jetbrains.intellij.ce",
	"com.jetbrains.pycharm",
	"com.jetbrains.pycharm.ce",
]);

export const FILESYSTEM_SENTINELS = new Set(["com.apple.finder"]);
export const SYSTEM_SETTINGS_SENTINELS = new Set(["com.apple.systempreferences"]);
